### ISSUE TITLE
Update pre-release for 3.0.0rc3

### ISSUE THREAD

**Issue by zechrogers** [conda-forge/sqlacodegen-feedstock#14]
### Comment:

Can this package be updated for the latest pre-release, 3.0.0rc3, and per #11 would that follow the guidelines of going into an `rc` branch, or continue the status quo with the main channel?

**Comment by dhirschfeld** [comment]
In future I'll publish pre-releases to an `rc` branch, but for now, the plan is to publish the `3.0.0rc*` versions to the main branch.

In that way, when people install this package they will at least get the *latest* RC version rather than having the default be an outdated RC version.
